[project]
name = "app-helper-cli"
version = "0.1.0"
description = "CLI tool to improve devX for webapps"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer>=0.21.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.14.10",
]
